### ISSUE TITLE
Acquire/release migration lock to prevent concurrent migration?

### ISSUE THREAD

**Issue by jemc** [tarolandia/cassandra-schema#2]
Currently, it's possible to screw things your `schema_information` consistency by migrating the same database concurrently (such as in automation that's running your deployment + migration in multiple datacenters, triggered by the same deploy).

When using high consistency modes, Cassandra can be used as a lock server.

Implementing a simple Cassandra-based lock could prevent concurrent migrations from clobbering eachother.

**Comment by tarolandia** [comment]
After some investigation I was able to find two main problems here: 

The first problem is related to [this line](https://github.com/tarolandia/cassandra-schema/blob/master/lib/cassandra-schema/migrator.rb#L14)

```ruby
 @current_version = get_current_version || init_versioning
```

This line represents a `READ` which is tied to the Consistency level defined by the connection object passed to the Migrator. If it can't read the current version, it will init versioning by doing a `WRITE`, which is not implemented as a LWT.

The following scenario is possible:

* Node 1 runs migrations: init versioning and start running migrations
* Node 2 runs migrations and the write operation from Node 1 is not propagated yet:  Node 2 reads with a `local_one` consistency and inits versioning again, screwing `schema_information` table.

To solve this problem I'm panning to implement `init_versioning` as a LWT and move it into ` generate_migrator_schema!`. This way we will be sure that the Migrator will never set `version` to `0` due to a race condition.

Additionally, I would do the `READ` with a higher consistency level.

**Comment by tarolandia** [comment]
The second problem is more complex and requires a different approach. Let's say that Node 1 starts running migrations, from `11` to `20`. In the middle of that process Node 2 starts running migrations and reads that the current version is `10` (because Node 1 will write version when it finishes running the migration process). Node 2 will try to apply `11` and will fail. As a rollback policy, it will write that current version is still `10`. This last write will compete with Node 1's write, which could cause an invalid state on the `schema_information` table.

To solve this problem I think the best approach would be to lock the table while a Node is running migrations. Other nodes trying to run migrations will detect that the table is locked and refuse to start the process.

```
Node1.lock
Node1.run_migration

Node2.lock
=> `schema_information` is locked

Node1.release

Node2.lock
Node2.run_migrations
```
